[package]
name = "cmd_runner"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
serde = "1.0.180"
serde_yaml = "0.9.25"
structured-logger = "1.0.2"
rand = "0.8.5"
